let
    Source = Excel.Workbook(File.Contents("<<PATH>>\All.txt.combined - complete_Figures - v2.0.xlsx"), null, true),
    _ResultsSources_Table = Source{[Item="SwarmResult",Kind="Table"]}[Data],
    #"Renamed Columns2" = Table.RenameColumns(_ResultsSources_Table,{{"Confusion matrix result", "Confusion Matrix"}, {"Classification report result.Source", "Classification report result"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Source.Name", type text}, {"Experiment Name", type text}, {"ModelName", type text}, {"Dataset", type text}, {"Scenario", type text}, {"Node", type text}, {"Experiment", type text}, {"Permutation", type text}, {"Experiment Time", type datetime}, {"TRAIN.TOTAL", Int64.Type}, {"TRAIN.CASE", Int64.Type}, {"TRAIN.CONTROL", Int64.Type}, {"TEST.TOTAL", Int64.Type}, {"TEST.CONTROL", Int64.Type}, {"TEST.CASE", Int64.Type}, {"Test accuracy", type number}, {"Permutation Name", type text}, {"Results", type text}, {"Confusion Matrix", type text}, {"Classification report result", type text}, {"Folder Path", type text}, {"Experiment_Node", type text}, {"DS_SC_EX", type text}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Permutation Name", "Permutation Name - Copy"),
    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Permutation Name - Copy", "Permutation Name 1"}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Renamed Columns", "Permutation Name 1", Splitter.SplitTextByEachDelimiter({"_"}, QuoteStyle.Csv, false), {"Permutation Name 1.1", "Permutation Name 1.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Permutation Name 1.1", type text}, {"Permutation Name 1.2", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"Permutation Name 1.2", "Permutation Number"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"TRAIN.TOTAL - Copy", Int64.Type}, {"TRAIN.TOTAL.Source", Int64.Type}, {"TRAIN.CONTROL.Source", Int64.Type}, {"TRAIN.CASE.Source", Int64.Type}, {"MaxTrainperPermutation", Int64.Type}, {"SW_Select", Int64.Type}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type2",":","",Replacer.ReplaceText,{"DS_SC_EX"}),
    #"Trimmed Text" = Table.TransformColumns(#"Replaced Value",{{"Dataset", Text.Trim, type text}, {"Scenario", Text.Trim, type text}, {"Experiment", Text.Trim, type text}, {"Experiment_Node", Text.Trim, type text}}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Trimmed Text",{{"precision 0", type number}, {"Specificity", type number}, {"F1 0", type number}, {"precision 1", type number}, {"Sensitivity", type number}, {"F1 1", type number}}),
    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type3","node_","",Replacer.ReplaceText,{"Experiment_Node"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","sw","swarm",Replacer.ReplaceText,{"Experiment_Node"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Replaced Value2",{{"Experiment_Node", "nodes"}, {"Permutation Number", "permutations"}, {"Test accuracy", "Accuracy"}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Renamed Columns3", "Experiment Name", "Experiment Name - Copy"),
    #"Split Column by Delimiter1" = Table.SplitColumn(#"Duplicated Column1", "Experiment Name - Copy", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Experiment Name - Copy.1", "Experiment Name - Copy.2"}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Experiment Name - Copy.1", type text}, {"Experiment Name - Copy.2", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type4",{"Experiment Name - Copy.1"}),
    #"Merged Columns" = Table.CombineColumns(#"Removed Columns",{"Experiment Name - Copy.2", "runSampleID"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"runSampleID.1"),
    #"Renamed Columns4" = Table.RenameColumns(#"Merged Columns",{{"runSampleID.1", "runSampleID"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns4", each not Text.Contains([Source.Name.BaseFile], "node_4_sw_") and not Text.Contains([Source.Name.BaseFile], "node_5_sw_") and not Text.Contains([Source.Name.BaseFile], "node_6_sw_"))
in
    #"Filtered Rows"